name: 'Check correct version'
on:
  pull_request:
    branches:
      - release/**
jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hola, JAir esta modificando este pack
    #main: '.github/workflows/check-version/index.js'