name: 'Check Version'
author: 'Jair Almaraz Saldaña'
inputs:
  GITHUB_TOKEN:
    description: 'Github Token'
    required: true
on:
  pull_request:
    branches:
      - release/**
jobs:
  check-version:
    runs:
      using: 'node16'
      main: 'index.js'
